services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - ../sandbox:/opt/game:ro
      - ../carimbo/src:/opt/src:ro
      - ../carimbo/build:/opt/engine:ro
      - /var/run/docker.sock:/var/run/docker.sock
  redis:
    image: redis:latest
    container_name: redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 1s
      retries: 3
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - storage:/data

volumes:
  storage:
