artifacts:
  - name: Henrique
    runtime: 1.0.2
    organization: carimbolabs
    repository: henrique
    release: 0.0.27
    resolution: 480p

  - name: MegaRick
    runtime: 1.0.10
    organization: carimbolabs
    repository: megarick
    release: 1.0.7
    resolution: 720p
