artifacts:
  - name: Slime
    cover: cover.png
    runtime: 1.0.42
    organization: willtobyte
    repository: slime
    release: 1.0.4
    resolution: 720p
    about: |
      # **Slime**

      An apocalyptic hand trying to shape the ideas of a slime.

      ## How to Play

      You’ll need **two controllers**:
      One controls the slime and the other the hand.

      Use directional buttons to move and attack.

      ### Gameplay Mechanics
      - Each player tries to **deceive** the other and then **attack**.
      - The first to **successfully attack** earns a point.

      ## Authors

      - **Pixel Art**: [Alyson Monteiro](https://alysonkof.com.br)
      - **Programming**: [Rodrigo Delduca](https://rodrigodelduca.com.br)

      Crafted with **[Carimbo](https://github.com/willtobyte/carimbo)**.

      ## Platforms

      This game is designed for **desktop web browsers only**.

      Check out the **source code** on [GitHub](https://github.com/willtobyte/slime).

      ### Press *any key* to continue

  - name: MegaRick
    cover: cover.png
    runtime: 1.0.30
    organization: willtobyte
    repository: megarick
    release: 1.0.30
    resolution: 720p

  - name: Henrique
    cover: cover.png
    runtime: 1.0.2
    organization: willtobyte
    repository: henrique
    release: 0.0.27
    resolution: 480p
