artifacts:
  - name: MOS6502
    cover: /media/MOS6502/cover.png
    runtime: "1.0.43"
    organization: willtobyte
    repository: MOS6502
    release: "1.0.6"
    resolution: 480p
    about: |
      **MOS6502 in pure Lua**

      Check out the **source code** on [GitHub](https://github.com/willtobyte/MOS6502).

  - name: Slime
    cover: /media/slime/cover.avif
    runtime: "1.0.45"
    organization: willtobyte
    repository: slime
    release: "1.0.7"
    resolution: 720p
    about: |
      # **Slime**

      An apocalyptic hand trying to shape the ideas of a slime.

      ## How to Play

      You’ll need **two controllers**:
      One controls the slime and the other the hand.

      Use directional buttons to move and attack.

      ### Gameplay Mechanics
      - Each player tries to **deceive** the other and then **attack**.
      - The first to **successfully attack** earns a point.

      ## Authors

      - **Pixel Art**: [Alyson Monteiro](https://alysonkof.com.br)
      - **Programming**: [Rodrigo Delduca](https://rodrigodelduca.com.br)

      Crafted with **[Carimbo](https://github.com/willtobyte/carimbo)**.

      ## Platforms

      This game is designed for **desktop web browsers only**.

      Check out the **source code** on [GitHub](https://github.com/willtobyte/slime).

      ### Press *any key* to continue

  - name: MegaRick
    cover: /media/megarick/cover.png
    runtime: "1.0.30"
    organization: willtobyte
    repository: megarick
    release: "1.0.30"
    resolution: 720p
    about: |
      # **MegaRick**

      An evil green octopus trying to stop Henrique from saving his mother.

      ## How to Play

      Use the arrow keys to move and the spacebar to shoot.

      ## Authors

      - **Pixel Art**: [Aline Bulcão](https://linktr.ee/dandelion.pixelart)
      - **Programming**: [Rodrigo Delduca](https://rodrigodelduca.com.br)

      Crafted with **[Carimbo](https://github.com/willtobyte/carimbo)**.

      ## Platforms

      This game is designed for **desktop web browsers only**.

      Check out the **source code** on [GitHub](https://github.com/willtobyte/megarick).

      ### Press *any key* to continue

  - name: Henrique
    cover: /media/generic/480x270.svg
    runtime: "1.0.2"
    organization: willtobyte
    repository: henrique
    release: "0.0.27"
    resolution: 480p
    about: |
      # **Henrique, the little apple critter, that little red one, you know?**

      A cheeky little apple worm!

      Code written by ChatGPT.

      ## How to Play

      Use the WASD keys to move.

      ## Authors

      - **Programming**: [ChatGPT 3.5](https://openai.com)

      Crafted with **[Carimbo](https://github.com/willtobyte/carimbo)**.

      ## Platforms

      This game is designed for **desktop web browsers only**.

      Check out the **source code** on [GitHub](https://github.com/willtobyte/henrique).

      ### Press *any key* to continue
