artifacts:
  - name: Henrique
    runtime: 1.0.2
    organization: willtobyte
    repository: henrique
    release: 0.0.27
    resolution: 480p

  - name: MegaRick
    runtime: 1.0.30
    organization: willtobyte
    repository: megarick
    release: 1.0.30
    resolution: 720p
    authors:
      - name: Rodrigo Delduca
        role: Developer & Game Designer
        website: https://rodrigodelduca.com.br

  - name: Slime
    runtime: 1.0.41
    organization: willtobyte
    repository: slime
    release: 1.0.1
    resolution: 720p
    authors:
      - name: Rodrigo Delduca
        role: Developer & Game Designer
        website: https://rodrigodelduca.com.br
