artifacts:
  - name: Slime
    cover: cover.png
    runtime: 1.0.41
    organization: willtobyte
    repository: slime
    release: 1.0.3
    resolution: 720p
    about: |
      ## Slime
      An apocalyptic hand trying to shape the ideas of a slime.

      #### How to play
      You will need two controllers to play: the first one controls the slime, and the second controls the hand. Use the directional buttons to move and a button to attack.

      One must try to deceive the other and then attack. Whoever attacks first earns the point.

      #### Authors
      * Pixel Art by Alyson Monteiro [alysonkof.com.br](https://alysonkof.com.br)
      * Programming by Rodrigo Delduca [rodrigodelduca.com.br](https://rodrigodelduca.com.br)

      Made with [Carimbo](https://github.com/willtobyte/carimbo)

      ***Any key to continue***

  - name: MegaRick
    cover: cover.png
    runtime: 1.0.30
    organization: willtobyte
    repository: megarick
    release: 1.0.30
    resolution: 720p

  - name: Henrique
    cover: cover.png
    runtime: 1.0.2
    organization: willtobyte
    repository: henrique
    release: 0.0.27
    resolution: 480p
