x-logging: &logging
  driver: syslog
  options:
    syslog-address: "udp://logs2.papertrailapp.com:33444"
    tag: "{{.Name}}/{{.ID}}"

services:
  app:
    logging:
      <<: *logging
  cloudflare:
    logging:
      <<: *logging
